name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
      
    - name: Install dependencies
      run: |
       npm install
       npm i pkg -g

      
    - name: Build executable
      run: npm run build
    
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: true
    
  upload-windows:
    runs-on: ubuntu-latest
    needs: release
    environment: windows
    steps:

    - name: Upload Windows executable
      uses: actions/upload-artifact@v2
      with:
        name: classesjs-win
        path: dist/classesjs-win.exe
    
  upload-linux:
    runs-on: ubuntu-latest
    needs: release
    environment: linux
    steps:

    - name: Upload Linux executable
      uses: actions/upload-artifact@v2
      with:
        name: classesjs-linux
        path: dist/classesjs-linux

  upload-macos:
    runs-on: ubuntu-latest
    needs: release
    environment: macos
    steps:

    - name: Upload macOS executable
      uses: actions/upload-artifact@v2
      with:
        name: classesjs-macos
        path: dist/classesjs-macos
